### ISSUE TITLE
Export environnement variables

### ISSUE THREAD

**Issue by NicolasCD** [saagie/gradle-saagie-plugin#1]
It could be interessting to export/import environnement variables. If possible with these options : 
 - ImportAllVariables
 - ImportVariables (with list of variables in a properties file)
 - ExportAllVariables
 - ExportVariables (with list of variables in a properties file)

**Comment by erwan-koffi** [comment]
Password variables are not accessible through public api. Therefore it is impossible to export them using this plugin.
Is it still interesting to work only on non secure ones?

**Comment by NicolasCD** [comment]
Yes it is interesting to have variables without password.

**Comment by erwan-koffi** [comment]
Closed in 2.1.0
