### ISSUE TITLE
Export individuals jobs KO

### ISSUE THREAD

**Issue by NicolasCD** [saagie/gradle-saagie-plugin#3]
In Windows environnement, Gradle 4.3 and 2.0.5 plugin, when exporting a list of jobs in an archive only the last one is saved in the archive.
Attached an example of build.gradle
[build.zip](https://github.com/saagie/gradle-saagie-plugin/files/1453334/build.zip)

**Comment by erwan-koffi** [comment]
Correction in 2.1.0
